# fill-in with real values, kubectl apply -f crawler-secret.yaml -n gfap
apiVersion: v1
kind: Secret
metadata:
  name: gfap-secret
  namespace: gfap
type: Opaque
stringData:
  VIDLII_USERNAME: "your-username"
  VIDLII_PASSWORD: "your-password"
  STATIC_PROXY_URLS: "http://user:pass@ip:port/,..."
  ROTATING_PROXY_URL: "http://user:pass@host:port/"